import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated from the folder structure — the first minimal instance of
// the planned Resources section (templates and checklists for learners,
// distinct from templates/ which is contributor/authoring-only material).
const sidebars: SidebarsConfig = {
  resourcesSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
