import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated from the folder structure so new learning paths and modules
// (see docs/architecture/CURRICULUM_ARCHITECTURE.md) appear automatically —
// ordering comes from each path's _category_.json `position` field.
const sidebars: SidebarsConfig = {
  learningPathsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
